version: "3"
services:
  nodeserver:
    build:
      context: .
    ports:
      - "8080:8080"
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"